apiVersion: apps/v1
kind: Deployment
metadata:
  name: SRE-Test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: SRE-Test-app
  template:
    metadata:
      labels:
        app: SRE-Test-app
    spec:
      containers:
      - name: SRE-Test-app
        image: SRE-Test-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret


